let products = [
{  
alt: "hammerstout",
caption: "hammerstout",
category_slug: "short",
category_type: "Boardshort",
category_type_slug: "boardshort",
description: "<p>Lightweight twill cotton</p><p>Dry-fast material</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#969696",
id: 133,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552749203/Cruise%20gray/boardshort_grey_web_1.jpg",
name: "Cruise",
original_color: "grey",
product_id: 133,
public_id: "Cruise gray/boardshort_grey_web_1",
regular_price: 160000,
slug: "cruise",
tag: "",
},
{ 
alt: "hammerstout",
caption: "hammerstout",
category_slug: "headwear",
category_type: "6 Panel",
category_type_slug: "6-panel",
description: "<p>Lightweight twill cotton</p><p>Embroidered circle logo</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#194d33",
id: 131,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552748974/Circle%20Logo%206%20panel/snapback_green_logo_web_1.jpg",
name: "Circle Logo",
original_color: "green",
product_id: 131,
public_id: "Circle Logo 6 panel/snapback_green_logo_web_1",
regular_price: 129000,
slug: "circlelogo",
tag: "",
},
{
alt: "hammerstout",
caption: "hammerstout",
category_slug: "headwear",
category_type: "Dad Hat",
category_type_slug: "dad-hat",
description: "<p>Lightweight twill coton</p><p>Embroidered circle logo</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#fffdd0",
id: 130,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552748762/logo%20dad%20hat/caps_brown_logo_web_1.jpg",
name: "Circle Logo",
original_color: "cream",
product_id: 130,
public_id: "logo dad hat/caps_brown_logo_web_1",
regular_price: 129000,
slug: "circlelogo",
tag: "",
},
{  
alt: "hammerstout",
caption: "hammerstout",
category_slug: "tshirts",
category_type: "Shortsleeve",
category_type_slug: "shortsleeve",
description: "<p>100% mid-weight cotton</p><p>Oil-base screenprinted on chest</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#FAFAFA",
id: 129,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552748423/WASTED/Wasted_web_1.jpg",
name: "Wasted",
original_color: "white",
product_id: 129,
public_id: "WASTED/Wasted_web_1",
regular_price: 139000,
slug: "wasted",
tag: "",
},
{ 
alt: "hammerstout",
caption: "hammerstout",
category_slug: "tshirts",
category_type: "Shortsleeve",
category_type_slug: "shortsleeve",
description: "<p>100% mid-weight cotton</p><p>Oil-base screenprinted on chest</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#FAFAFA",
id: 128,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552748327/BABY%20ANGEL/T-Shirt_Little_Angel_web_1.jpg",
name: "Baby Angel",
original_color: "white",
product_id: 128,
public_id: "BABY ANGEL/T-Shirt_Little_Angel_web_1",
regular_price: 139000,
slug: "babyangel",
tag: "",
},
{ 
alt: "hammerstout",
caption: "hammerstout",
category_slug: "bags",
category_type: "Waist Bag",
category_type_slug: "waist-bag",
description: "<p>2 main storage</p><p>1 mesh slip inside</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#194d33",
id: 127,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552748151/groose%20waist/waist_bag_green_web_1.jpg",
name: "Groose",
original_color: "green",
product_id: 127,
public_id: "groose waist/waist_bag_green_web_1",
regular_price: 165000,
slug: "groose",
tag: "",
},
{
alt: "hammerstout",
caption: "hammerstout",
category_slug: "bags",
category_type: "Shoulder Bag",
category_type_slug: "shoulder-bag",
description: "<p>Cordura material</p><p>Phone pocket</p><p>1 Coin pocket</p><p>1 mesh slip inside</p><p>16cm x 17cm x 6cm</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#000000",
id: 126,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552747898/shoulder%20bag/Shoulder_bag_web_1.jpg",
name: "Shadow",
original_color: "black",
product_id: 126,
public_id: "shoulder bag/Shoulder_bag_web_1",
regular_price: 165000,
slug: "shadow",
tag: "",
},
{ 
alt: "hammerstout",
caption: "hammerstout",
category_slug: "short",
category_type: "Cargo",
category_type_slug: "cargo",
description: "<p>&nbsp;</p><p>Mid-weight Twill</p><p>Zipper fly</p><p>2 front pockets</p><p>2 back pockets</p><p>2 side utility pockets</p>",
discount_percentage: null,
discount_value: null,
hex_color: "#969696",
id: 125,
link: "https://res.cloudinary.com/hammerstoutdenim/image/upload/q_auto/f_auto/v1552747444/charcoal%20cargo/Short_Cargo_Dark_Grey_web_1.jpg",
name: "Charcoal",
original_color: "grey",
product_id: 125,
public_id: "charcoal cargo/Short_Cargo_Dark_Grey_web_1",
regular_price: 245000,
slug: "charcoal",
tag: "",
}
    ]