export const GET_ERRORS = 'GET_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const SET_CSRF = 'SET_CSRF';


//PRODUCT
export const LOADING_PRODUCT ='LOADING_PRODUCT';
export const GET_PRODUCT_HIGHLIGHT = 'GET_PRODUCT_HIGHLIGHT';
export const STOP_LOADING_PRODUCT ='STOP_LOADING_PRODUCT';
export const GET_PRODUCT_WITH_QUERY ='GET_PRODUCT_WITH_QUERY';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';

// Cart
export const LOADING_CART = 'LOADING_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const STOP_LOADING_CART = 'STOP_LOADING_CART';
export const FETCH_CART_LIST = 'FETCH_CART_LIST';
export const UPDATE_CART_LIST = 'UPDATE_CART_LIST';
export const DELETE_CART_LIST = 'DELETE_CART_LIST';
export const CLEAR_CART_LIST = 'CLEAR_CART_LIST';

// Auth
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const LOADING_AUTH_USER = 'LOADING_AUTH_USER';
export const LOGIN_WITH_GOOGLE ='LOGIN_WITH_GOOGLE';
export const AUTH_USER_LOGOUT = 'AUTH_USER_LOGOUT';
export const STOP_LOADING_AUTH ='STOP_LOADING_AUTH';

// Tracks
export const LOADING_TRACK = 'LOADING_TRACK';
export const FETCH_TRACK_TOKEN = 'FETCH_TRACK_TOKEN';

// MyAccount
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const GET_ADDRESS_USER = 'GET_ADDRESS_USER';
export const CLEAR_ADDRESS_USER = 'CLEAR_ADDRESS_USER';
export const SET_CURRENT_ADDRESS_USER ='SET_CURRENT_ADDRESS_USER';
// ADDRESS
export const GET_PROVINCE ='GET_PROVINCE';
export const LOADING_ADDRESS='LOADING_ADDRESS';
export const FIND_CITY_FROM_PROVINCE ='FIND_CITY_FROM_PROVINCE';
export const FIND_DISTRICT_FROM_REGENCY ='FIND_DISTRICT_FROM_REGENCY';
export const FIND_VILLAGE_FROM_DISTRICT ='FIND_VILLAGE_FROM_DISTRICT';
export const REMOVE_REGENCIES = 'REMOVE_REGENCIES';
export const REMOVE_DISTRICTS = 'REMOVE_DISTRICTS';

// notification
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const CLEAR_NOTIFICATION ='CLEAR_NOTIFICATION';

//shipping
export const CALCULATE_COST = 'CALCULATE_COST';
export const LOADING_SHIPPING = 'LOADING_SHIPPING';
export const STOP_LOADING_SHIPPING = 'STOP_LOADING_SHIPPING';
export const CLEAR_SHIPPING = 'CLEAR_SHIPPING';

// Category
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
export const LOADING_CATEGORY ='LOADING_CATEGORY';

// UI
export const LOADING_UI = 'LOADING_UI';
export const GET_CONTENT_HOME ='GET_CONTENT_HOME';

// LOOKBOOK
export const LOADING_LOOKBOOK ='LOADING_LOOKBOOK';
export const GET_ALL_LOOKBOOK ='GET_ALL_LOOKBOOK';
export const GET_DETAIL_LOOKBOOK ='GET_DETAIL_LOOKBOOK';

// COLLECTION
export const LOADING_COLLECTION = 'LOADING_COLLECTION';
export const GET_ALL_COLLECTION = 'GET_ALL_COLLECTION';
export const GET_DETAIL_COLLECTION = 'GET_DETAIL_COLLECTION';


// ORDER
export const LOADING_ORDER = 'LOADING_ORDER';
export const REMOVE_LOADING_ORDER = 'REMOVE_LOADING_ORDER';
export const SET_CURRENT_ORDER = 'SET_CURRENT_ORDER';
export const GET_ALL_ORDER = 'GET_ALL_ORDER';
export const SET_CURRENT_ORDER_PAYMENT = 'SET_CURRENT_ORDER_PAYMENT';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
// Voucher
export const SET_VOUCHER_DISCOUNT ='SET_VOUCHER_DISCOUNT';
export const LOADING_VOUCHER = 'LOADING_VOUCHER';
export const CLEAR_CURRENT_VOUCHER ='CLEAR_CURRENT_VOUCHER';
export const SET_CURRENT_VOUCHER = 'SET_CURRENT_VOUCHER';
export const CLEAR_LOADING_VOUCHER = 'CLEAR_LOADING_VOUCHER';

// Sizing
export const GET_ALL_SIZING ='GET_ALL_SIZING';
export const LOADING_SIZING ='LOADING_SIZING';

// Instagram
export const GET_INSTAGRAM_MEDIA_RECENT = 'GET_INSTAGRAM_MEDIA_RECENT';
export const LOADING_INSTAGRAM = 'LOADING_INSTAGRAM'